### PR TITLE
chore(all): update deps

### PR DESCRIPTION
**Pull request by Malinskiy**

### CODE REVIEW

**Comment by hannesa2** [comment]
I guess the double builds will disappear with https://github.com/Malinskiy/action-android/pull/61

**Comment by hannesa2** [comment]
Why not merge these in advance ?

image
These at least work

**Comment by Malinskiy** [comment]
The double builds are happening as a result of running for the tip of the branch (push) and the HEAD with the merged output from the target branch and the proposed change

**Comment by hannesa2** [comment]
> The double builds are happening as a result of running for the tip of the branch (push) and the HEAD with the merged output from the target branch and the proposed change. That's intended and can be read as `does it work on it's own` and `does it work if we merge it`

Maybe.
At least my fork removed the twice (and non-necessary) builds https://github.com/hannesa2/action-android/pull/17 by containing https://github.com/Malinskiy/action-android/pull/61

**Comment by Malinskiy** [comment]
I'm not forcing you to use any setup, I just explained why there are 2 builds and how they're different. If you navigate in the logs for the two builds you'll see for example
push:
```
HEAD is now at b387257 fix(all): update to TS4 for try-catch
```
pull_request:
```
HEAD is now at 2d8b051 Merge b387257f9eacad41055a74293f684ae388ac3aa7 into a8b313748036a9def32ed17cebceb932206bd74c
```

There is a case where only one of them fail

**Pull request merged**
